<?php

use Illuminate\Database\Seeder;
use App\LuckyDraw;
use App\Type;

class LuckyDrawTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $service_type_id = Type::find(1)->id;
        $second_service_type_id = Type::find(2)->id; 
        $lucky_draw_type_id = Type::find(3)->id;

        $service_lucky_draws = [
            ['Jem Picture,Griller',10,9],
            ['Rice Cooker (Panasonic)',11,19],
            ['Air Cooler(Master)',14,11],
            ['Refrigerator',15,12],
            ['Washing Machine(ALPHA)',17,4],
            ['TV(SAMSONIC)Air Can Mini(IP Camera)',26,10],
            ['Aircooler(SAMSONIC)',27,13],
            ['Kangroo Microwave',29,20],
            ['5BB ECO 10Mbps (1year)',36,3],
            ['Laptop (AUSU) 51 2nd',51,2],
            ['Air Cooler (Media)',57,14],
            ['Washing Machine(Nibban)',68,5],
            ['Washing Machine(Nibban)',69,6],
            ['Water Dispenser(Nibban)',70,7],
            ['Washing Machine (Alpha)',166,15],
            ['Air Cooler (Master)and Gold Earing',73,16],
            ['Microwave (Panasonic)',74,8],
            ['Air Cooler (Media)and Gold Earing',77,17],
            ['Air Cooler (GLACLER)',78,18],
            ['Gold Necklace',296,1],
            



            ['Skin Care Set (5Pcs)',1],
            ['Entia (Skin Care Set)',4],
            ['Entia (Skin Care Set)',5],
            ['Entia (Skin Care Set)',6],
            ['Entia (Skin Care Set)',7],
            ['Media Stand Fan + M.Watch',8],
            ['Air Cooler(Samsonic)',9],
            ['Rice Cooker+ M.Watch',12],
            ['City Mart Give Voucher',24],
            ['AC/DC Fan (K-Lite)',25],
            ['Keyboard & Mouse',28],
            ['Air Cooler(Samsonic)',37],
            ['5BB (50000Ks) Package',38],
            ['5BB (50000Ks) Package',39],
            ['Stand Fan (Media)+(20000ks)CM Gift Vocher',40],
            ['ADATA 2TB HardDick',44],
            ['Game Pad + Mouse+ M.Watch',46],
            ['Sai Cosmetic Gift',52],
            ['Sai Cosmetic Gift',53],
            ['Blanket',65],
            ['Blanket',66],
            ['Induction Cooker+ M.Watch',72],
            ['Stand Fan (SENKO)+(20000ks)CM Gift Vocher',79],
            ['Stand Fan',86],
            ['Plastic Cabinet+ M.Watch',115],
            ['Red Cooker Pot+ M.Watch',132],
            ['Red Cooker Pot+ M.Watch',133],
            ['Hot Pot cooker+ M.Watch',137],
            ['Rice Cooker+ M.Watch',138],
            ['Rice Cooker+ M.Watch',139],
            ['Air Cooler (MASUTA)',71],
            ['AirCooler(Master)',168],
            ['GP 7223+(20000ks)CM Gift Vocher',210],
            ['GP 7005+(20000ks)CM Gift Vocher',211],
            ['GP 7603 (Black) and Gold Earing',216],
            ['GP 7603 Rose Gold+(20000ks)CM Gift Vocher',217],
            ['Rice Cooker (Media)+(20000ks)CM Gift Vocher',244],
            ['Rice Cooker (Media)+(20000ks)CM Gift Vocher',245],
            ['Toaster (Big)+(20000ks)CM Gift Vocher',273],
            ['Measuring Scale+(20000ks)CM Gift Vocher',297],
            ['Measuring Scale+(20000ks)CM Gift Vocher',298],
            ['Measuring Scale+(20000ks)CM Gift Vocher',299],
            ['Measuring Scale+(20000ks)CM Gift Vocher',300]
        ];

        // Service prices.
        foreach($service_lucky_draws as $ld){
            if(count($ld) === 3){
                LuckyDraw::create([
                    'name' => $ld[0],
                    'number' => $ld[1],
                    'special_number' => $ld[2],
                    'type_id' => $service_type_id
                ]);
            } else {
                LuckyDraw::create([
                    'name' => $ld[0],
                    'number' => $ld[1],
                    'special_number' => null,
                    'type_id' => $service_type_id
                ]);
            }
        }

        $second_service_lucky_draws = [
            ['Kerasys(Shower,Shampoo and tooth past & Brush)',2],
            ['Kerasys(Shower,Shampoo and tooth past & Brush)',3],
            ['DVD Player',13],
            ['Coffee Maker',16],
            ['Vitora Secret Cosmetics',18],
            ['Vitora Secret Cosmetics',19],
            ['Vitora Secret Cosmetics',20],
            ['Vitora Secret Cosmetics',21],
            ['Vitora Secret Cosmetics',22],
            ['Vitora Secret Cosmetics',23],
            ['Portable Gas Stove',30],
            ['Stand Fan (Media)',31],
            ['Stand Fan (Media)',32],
            ['Stand Fan (Media)',33],
            ['Table Fan',34],
            ['Table Fan (Media)',41],
            ['Coffee Grinder + Coffee Cup',42],
            ['Electric Kettle',43],
            ['Arctic Mini Air Cooler + Switchs',45],
            ['HeadPhone+Sefile Stick+Mouse',47],
            ['Mouse + Photo Album,Ushido Shampoo',50],
            ['7 Pieces Cookware Set',54],
            ['7 Pieces Cookware Set',55],
            ['7 Pieces Cookware Set',56],
            ['Table Fan',59],
            ['Table Fan',60],
            ['Table Fan',61],
            ['Wireless Speaker + Cosmetic',62],
            ['PowerBank+Album',63],
            ['PowerBank+LED+Cup',64],
            ['Rice Cooker',67],
            ['Jug Kettle & Octime Set',75],
            ['Jug Kettle & Octime Set',76],
            ['Slim Bag,Lip Stick, Coffee Cup,Steel Lunch Box',80],
            ['Slim Bag,Lip Stick, Coffee Cup,Steel Lunch Box',81],
            ['Slim Bag,Lip Stick, Coffee Cup,Steel Lunch Box',82],
            ['Stand Fan',83],
            ['Rice Cooker',84],
            ['Rice Cooker',85],
            ['Iron',87],
            ['Iron',88],
            ['Steel Luch Box',126],
            ['Steel Luch Box',127],
            ['Lunch Box with heat keeper',128],
            ['Lunch Box with heat keeper',129],
            ['Red Cooker Pot',130],
            ['Red Cooker Pot',131],
            ['3min Kettle',134],
            ['3min Kettle',135],
            ['Griller',136],
            ['Blender',140],
            ['Wood Desk',165],
            ['Stand Fan',167],
            ['Stand Fan',169],
            ['GP 7708',212],
            ['GP 7709',213],
            ['GP 7711',214],
            ['GP 7603 (Leather)',215],
            ['GP 7603 Silver',218],
            ['GP 7601 Black',219],
            ['GP 7720',220],
            ['Toaster',251],
            ['Toaster',252],
            ['Electric Kettle',266],
            ['Electric Kettle',267],
            ['Electric Kettle',268],
            ['Gas Cooker',269],
            ['Gas Cooker',270],
            ['Gas Cooker',271],
            ['Jar Pot',272],
            ['Luggage',274],
            ['Luggage',275]
        ];

        foreach($second_service_lucky_draws as $ld){
            LuckyDraw::create([
                'name' => $ld[0],
                'number' => $ld[1],
                'special_number' => null,
                'type_id' => $second_service_type_id
            ]);
        }

        $normal_lucky_draws = [
            ['Keep Warn Kettle (Lucky)',35],
            ['Wireless Mouse + Photo Album',48],
            ['Mouse + Photo Album',49],
            ['Kettle',58],
            ['Body Powder , Roll On and Shampoo',89],
            ['Body Powder , Roll On and Shampoo',90],
            ['Body Powder , Roll On and Shampoo',91],
            ['Body Powder , Roll On and Shampoo',92],
            ['Body Powder , Roll On and Shampoo',93],
            ['Body Powder , Roll On and Shampoo',94],
            ['Body Powder , Roll On and Shampoo',95],
            ['Body Powder , Roll On and Shampoo',96],
            ['Body Powder , Roll On and Shampoo',97],
            ['Body Powder , Roll On and Shampoo',98],
            ['Body Powder , Roll On and Shampoo',99],
            ['Body Powder , Roll On and Shampoo',100],
            ['Body Powder , Roll On and Shampoo',101],
            ['Body Powder , Roll On and Shampoo',102],
            ['Body Powder , Roll On and Shampoo',103],
            ['Body Powder , Roll On and Shampoo',104],
            ['Body Powder , Roll On and Shampoo',105],
            ['Body Powder , Roll On and Shampoo',106],
            ['Body Powder , Roll On and Shampoo',107],
            ['Body Powder , Roll On and Shampoo',108],
            ['Body Powder , Roll On and Shampoo',109],
            ['Body Powder , Roll On and Shampoo',110],
            ['Body Powder , Roll On and Shampoo',111],
            ['Body Powder , Roll On and Shampoo',112],
            ['Plastic stand for Shoes/ဖိနပ်စင်',113],
            ['Plastic stand for Shoes/ဖိနပ်စင်',114],
            ['Clothes Box',116],
            ['Clothes Box',117],
            ['Clothes Box',118],
            ['Clothes Box',119],
            ['Clothes Box',120],
            ['Blanket',121],
            ['Blanket',122],
            ['Blanket',123],
            ['Blanket',124],
            ['Noodle Pot and Coffee Cup',125],
            ['Ceramic Bowl Set',141],
            ['Slim Bag and Couple Coffee Cup',142],
            ['Slim Bag and Couple Coffee Cup',143],
            ['Slim Bag and Couple Coffee Cup',144],
            ['Buletooth Speaker',145],
            ['Buletooth Speaker',146],
            ['Buletooth Speaker',147],
            ['Buletooth Speaker',148],
            ['Buletooth Speaker',149],
            ['Lock & Lock Lunch Box',150],
            ['Lock & Lock Lunch Box',151],
            ['Lock & Lock Lunch Box',152],
            ['Lock & Lock Lunch Box',153],
            ['Lock & Lock Lunch Box',154],
            ['Lock & Lock Lunch Box',155],
            ['Lock & Lock Lunch Box',156],
            ['Lock & Lock Lunch Box',157],
            ['Lock & Lock Lunch Box',158],
            ['Lock & Lock Lunch Box',159],
            ['Luminarc Drink Set',160],
            ['Luminarc Drink Set',161],
            ['Luminarc Drink Set',162],
            ['Luminarc Drink Set',163],
            ['Luminarc Drink Set',164],
            ['Steel ပ်နးကနစင်',170],
            ['Steel ပ်နးကနစင်',171],
            ['Steel ပ်နးကနစင်',172],
            ['Steel ပ်နးကနစင်',173],
            ['Steel ပ်နးကနစင်',174],
            ['သံပ်နးကနစင် ၃ဆ့်',175],
            ['သံပ်နးကနစင် ၄ဆ့်',176],
            ['သံပ်နးကနစင် ၄ဆ့်',177],
            ['ကေကာ်ပ်နးကနစင်',178],
            ['ကေကာ်ပ်နးကနစင်',179],
            ['City Mart Give Voucher',180],
            ['City Mart Give Voucher',181],
            ['City Mart Give Voucher',182],
            ['City Mart Give Voucher',183],
            ['City Mart Give Voucher',184],
            ['City Mart Give Voucher',185],
            ['City Mart Give Voucher',186],
            ['City Mart Give Voucher',187],
            ['City Mart Give Voucher',188],
            ['City Mart Give Voucher',189],
            ['City Mart Give Voucher',190],
            ['City Mart Give Voucher',191],
            ['City Mart Give Voucher',192],
            ['City Mart Give Voucher',193],
            ['City Mart Give Voucher',194],
            ['Toy',195],
            ['Toy',196],
            ['Bathing Set,Glass Cup',197],
            ['Bathing Set,Glass Cup',198],
            ['Bathing Set,Glass Cup',199],
            ['Bathing Set,Glass Cup',200],
            ['Bathing Set,Glass Cup',201],
            ['Tea Set (6 pairs)',202],
            ['Tea Set (6 pairs)',203],
            ['Bloster',204],
            ['Bloster',205],
            ['Lunch Box Steel',206],
            ['Lunch Box Steel',207],
            ['Lunch Box Steel',208],
            ['Lunch Box Steel',209],
            ['Power Bank Herze',221],
            ['Power Bank Herze',222],
            ['Power Bank Herze',223],
            ['Power Bank Herze',224],
            ['Power Bank Herze',225],
            ['Power Bank Jane',226],
            ['Power Bank Jane',227],
            ['Power Bank Jane',228],
            ['Power Bank Jane',229],
            ['Power Bank Jane',230],
            ['Ear Phone 805',231],
            ['Ear Phone 805',232],
            ['Ear Phone 805',233],
            ['Ear Phone 805',234],
            ['Ear Phone 805',235],
            ['Noodle Pot & Steel Lunch Box',236],
            ['Noodle Pot & Steel Lunch Box',237],
            ['Noodle Pot & Steel Lunch Box',238],
            ['Noodle Pot & Steel Lunch Box',239],
            ['Noodle Pot & Steel Lunch Box',240],
            ['Rice Cooker',241],
            ['Rice Cooker',242],
            ['Rice Cooker',243],
            ['Rice Cooker',246],
            ['Rice Cooker',247],
            ['Lunch Box (Heat Keeper)',248],
            ['Lunch Box (Heat Keeper)',249],
            ['Lunch Box (Heat Keeper)',250],
            ['Vacuum Flask',253],
            ['Vacuum Flask',254],
            ['Vacuum Flask',255],
            ['Vacuum Flask',256],
            ['Vacuum Flask',257],
            ['Electric Kettle 3mins,Coffee Cup',258],
            ['Electric Kettle 3mins,Coffee Cup',259],
            ['Electric Kettle 3mins,Coffee Cup',260],
            ['Steam Iron',261],
            ['Steam Iron',262],
            ['Steam Iron',263],
            ['Steam Iron',264],
            ['Steam Iron',265],
            ['Medicare Gift Voucher',276],
            ['Medicare Gift Voucher',277],
            ['Medicare Gift Voucher',278],
            ['Medicare Gift Voucher',279],
            ['Medicare Gift Voucher',280],
            ['Medicare Gift Voucher',281],
            ['Medicare Gift Voucher',282],
            ['Medicare Gift Voucher',283],
            ['Medicare Gift Voucher',284],
            ['Medicare Gift Voucher',285],
            ['Medicare Gift Voucher',286],
            ['Medicare Gift Voucher',287],
            ['Medicare Gift Voucher',288],
            ['Medicare Gift Voucher',289],
            ['Medicare Gift Voucher',290],
            ['Medicare Gift Voucher',291],
            ['Medicare Gift Voucher',292],
            ['Medicare Gift Voucher',293],
            ['Medicare Gift Voucher',294],
            ['Medicare Gift Voucher',295],
            ['USHIDO Shampoo and Steel Lunch Box',301],
            ['USHIDO Shampoo and Steel Lunch Box',302],
            ['USHIDO Shampoo and Steel Lunch Box',303],
            ['USHIDO Shampoo and Steel Lunch Box',304],
            ['USHIDO Shampoo and Steel Lunch Box',305],
            ['USHIDO Shampoo and Steel Lunch Box',306],
            ['USHIDO Shampoo and Steel Lunch Box',307],
            ['USHIDO Shampoo and Steel Lunch Box',308],
            ['USHIDO Shampoo and Steel Lunch Box',309]
            










        ];

        // Normal lucky draws
        foreach($normal_lucky_draws as $ld){
            LuckyDraw::create([
                'name' => $ld[0],
                'number' => $ld[1],
                'special_number' => null,
                'type_id' => $lucky_draw_type_id
            ]);
        }
    }
}
