<?php

use Illuminate\Database\Seeder;
use App\Type;
use App\Staff;

class StaffTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $service_type_id = Type::find(1)->id;
        $second_service_type_id = Type::find(2)->id;
        $lucky_draw_type_id = Type::find(3)->id;

        $service_staffs = [
            ['NWE NWE AUNG','Dir'],
            ['WAI NWE SOE','Con'],
            ['THEINT LWIN WIN','SV'],
            ['WARSO WATHONE OO','IA'],
            ['NANG MYA MU','SV'],
            ['THAE MYAT NOE PAING','AS'],
            ['THANT ZAW HTET','HD'],
            ['YIN MIN PHYO','MNG'],
            ['NANN KHIN THUZAR KYAW','SV'],
            ['LWIN MAR OO','MNG'],
            ['YE LYNN MIN','D'],
            ['HNIN HNIN NWAY','C'],
            ['ZARNI HTET','HD'],
            ['WAI YAN TUN','IE'],
            ['SU TAR HLAING','HD'],
            ['MAR LAR NWE','HD'],
            ['KHIN YUPAR AYE','MNG'],
            ['WINT PHYU PHYU MAUNG','TRN'],
            ['MAY ZIN AYE','AS'],
            ['MYO MIN MIN LIN','MNG'],
            ['TIN MAR LWIN','AS'],
            ['WAI WAI THAN','JA'],
            ['KYI CHAN NYEIN','HD'],
            ['SANN THIHA THU','MNG'],
            ['TIN MAY WIN','MNG'],
            ['SU THIRI KYAW','AS'],
            ['THET AUNG OO','MNG'],
            ['KHANT ZIN AUNG','SV'],
            ['TIN NILAR WIN','AS'],
            ['THANT ZIN HTWE','AS'],
            ['SHINE LIN KYAW','AS'],
            ['KAY KHINE SOE','MNG'],
            ['CHAW KALAYAR MYINT','MNG'],
            ['HTET HTET SAN','MNG'],
            ['WAR WAR TUN','AS'],
            ['PHYU HNIN OO','IC'],
            ['THET THET KHINE','MNG'],
            ['THIN LAE YI WIN','MNG'],
            ['MIN MAUNG MYINT','IC'],
            ['YOON MYAT THIRI','MNG'],
            ['SHWE SHWE THIEN','IC'],
            ['AUNG ZAY MYINT','AS'],
            ['PAN MYINT MO AYE','AS'],
            ['AYE CHAN MOE','IC'],
            ['MYO MYINT SAN','TRN'],
            ['NANDAR LIN PYAE','IC'],
            ['THANDAR KHIN','AS'],
            ['SU YAMIN HLAING','MNG'],
            ['WIN WIN NWE','IC'],
            ['WAI YAN SOE51','AS'],
            ['MARN PAING TUN TUN','MNG'],
            ['AYE NYEIN THU','AS'],
            ['THIRI KYAW KYAW','PHA'],
            ['AYE CHAN MOE','MNG'],
            ['KYAW MYINT TUN','MNG'],
            ['KO KO HTAY','AS'],
            ['THEINT THU THU AUNG','MNG'],
            ['MOH MOH THIN ZAW','IC'],
            ['LIN LIN THU','MNG'],
            ['MOE THET WAI','AS'],
            ['KHIN CHAN MYAE LIN','AS'],
            ['KHIN SU SU LWIN','IC'],
            ['WAIYAN HTUT','AS']
        ];

        $second_service_staffs = [
            ['NYAN WIN MAUNG','AS'],
            ['HSU MYAT NEW','AS'],
            ['PHUE PHUE PWINT MAY','AS'],
            ['PYAE PHYO WIN','AS'],
            ['THIDA SWE ZIN','AS'],
            ['ZIN PHYO OO','GD'],
            ['KYI SU AUNG','AS'],
            ['NILAR KHAING','AS'],
            ['SU WAI LWIN','SV'],
            ['SANDI WIN MYAT','SV'],
            ['AYE CHAN MYA','AS'],
            ['THAN KHIN SHWE','MNG'],
            ['MIN KYAW THU','AS'],
            ['AUNG HTET LWIN','AS'],
            ['Kyaw Thet Wai','AS'],
            ['SU NADI NAING','AS'],
            ['KAY ZAR WIN','AS'],
            ['MIN SAT MAW','INT'],
            ['ZAYYAR MIN WAI','AS'],
            ['EAINDRA MOE AUNG','AS'],
            ['MAY THU SOE','IC'],
            ['LAY LAY MON','AS'],
            ['HTET WAIHYLAN HTUT','MNG'],
            ['YING HOM YUNT','PHA'],
            ['WAI WAI NAING','IC'],
            ['THUZAR SOE MYINT','PHA'],
            ['WUTT YI PHYO','AS'],
            ['WIN ZAW OO','AS'],
            ['HNIN HTET HTET HLAING','AS'],
            ['SHWE YI OO','AS'],
            ['SAUNG EAINDARY OO','MNG'],
            ['EI SU HTAY','PHA'],
            ['SAW YU NWE S9','PHA'],
            ['THAW THAW NAING','AS'],
            ['HSU HLAING MON','MNG'],
            ['KHIN MAY NYUNT','PHA'],
            ['EI MON KYAW','AS'],
            ['THET WADI KYAW','AS'],
            ['MON MON THANT','AS'],
            ['WAI ZIN AUNG','AS'],
            ['PYAE PHYO ZAW','AS'],
            ['THAE HSU PYAE SONE','PHA'],
            ['YE MIN','AS'],
            ['KHIN CHO OO','MNG'],
            ['KHIN THINZAR ZAW','PHA'],
            ['AUNG YE ZAW','AS'],
            ['HSU WAI HTET','MNG'],
            ['HNIN THANDAR AUNG','PHA'],
            ['LIN LIN HTET','IC'],
            ['MYO MIN ZAW','MNG'],
            ['SU HLAING HNIN','AS'],
            ['AUNG PHYO PAING','AS'],
            ['NANDAR AUNG','AS'],
            ['EI MON MON THAE','PHA'],
            ['WAI YAN TUN','AS'],
            ['THURA ZAW','AS'],
            ['THIN THIN WAI','AS'],
            ['HEIN KHANT WIN','PHA'],
            ['HLWAN MOE AUNG','AS'],
            ['NAW THAZIN HTOO','MNG'],
            ['MYO HSU MON KYAW','PHA'],
            ['AUNG MYO','AS'],
            ['ZIZAWAR THIN','AS'],
            ['AYE KAY THI','AS'],
            ['PHYO NANDAR THEINT','AS'],
            ['SAW HTET NANDI','MNG'],
            ['THAW ZIN HTAY','AS'],
            ['MAY THU ZAW','PHA'],
            ['WAR WAR TUN','PHA'],
            ['THUZAR MON','PHA'],
            ['HONEY THANT ZIN','MNG'],
            ['CHO CHO WIN','AS']
        ];

        $lucky_draw_staffs = [
            ['NWAY NWAY AUNG','ACT'],
            ['AUNG MYO HTUT','IE'],
            ['KYAW HLAING SOE','GD'],
            ['AYE CHAM MYINT','AS'],
            ['HAY MARN WIN MAUNG','SV'],
            ['KAUNG MAW HTOO','SV'],
            ['KAUNG KHANT ZAW','AS'],
            ['RENA ROSS','AS'],
            ['THURAIN PHYO','AS'],
            ['PYAE PHYO AUNG','SV'],
            ['THINZAR AUNG','AS'],
            ['SITHU AUNG','AS'],
            ['PYAE PHYO HLAING','AS'],
            ['NWAY NWAY HLAING','AS'],
            ['ZIN WIN MAR','PHA'],
            ['YADANAR PHYOE','AS'],
            ['THANT ZIN HTUT','AS'],
            ['THAN THAN SINT','AS'],
            ['KAY THI MOE','AS'],
            ['NAY ZAW AUNG','AS'],
            ['ZIN MIN TUN','AS'],
            ['KHINE THIN NEW','AS'],
            ['MYINT MYAT MON','AS'],
            ['CHO ME THAN NAING','AS'],
            ['HSU MYAT SOE','PHA'],
            ['DAUNG SAI','PHA'],
            ['HONEY LIN','AS'],
            ['HTET MYAT AUNG','AS'],
            ['NAY CHI LWIN','AS'],
            ['MYAT THEINGI','AS'],
            ['YE AUNG KYAW','TRN'],
            ['AYE MYAT MOE','PHA'],
            ['MOE HNIN PHYU','AS'],
            ['SOE SANDAR LWIN','PHA'],
            ['SAUNG THEINGI WIN MYO','PHA'],
            ['YAMIN KO KO','TRN'],
            ['NAY THURAIN ZAW','AS'],
            ['SU SU HTET','AS'],
            ['MYO MIN KYAW','PHA'],
            ['SOE SANDI PHUE','PHA'],
            ['HNIN OO WAI','AS'],
            ['NYUT NYUT HTAY','AS'],
            ['MAY THAGYAN OO','AS'],
            ['ZIN THU THU HLAING','AS'],
            ['MYA THAZIN','AS'],
            ['KYAW ZIN LATT','AS'],
            ['THET MIN OO','AS'],
            ['SU LATT PYAE','AS'],
            ['EI NANDAR ZAW','PHA'],
            ['SAW MAW KAIR DO','IC'],
            ['THAW ZIN','AS'],
            ['WUTT YI MON','TRN'],
            ['THAN TUN MAUNG','AS'],
            ['ZIN NYEIN OO','AS'],
            ['SAN THEINGI','AS'],
            ['KHINE WATHONE MOE','PHA'],
            ['MYA NANDAR AUNG','PHA'],
            ['AYE MAR','AS'],
            ['THAN TOE AUNG','AS'],
            ['SABEI HLAING','AS'],
            ['EI THET KHINE','IC'],
            ['PAING WAI YAN HTET','AS'],
            ['MOE SANDAR WIN','PHA'],
            ['POE EI PHYU','AS'],
            ['PANN THAZIN KHINE','PHA'],
            ['AUNG KYAW SINT','IC'],
            ['AUNG THU MYINT','AS'],
            ['YADANAR KHIN','AS'],
            ['YE HTUT NAUNG','AS'],
            ['TUN TUN LIN','AS'],
            ['SU MYAT NOE','AS'],
            ['PHOO PWINT MAY','PHA'],
            ['MIN THWAY SAN','PHA'],
            ['SOE THANDAR','AS'],
            ['HAN MYO NYEIN','AS'],
            ['PHYO ZAYYAR SWE','AS'],
            ['KHIT YADANA','PHA'],
            ['HSU YAMIN THU','PHA'],
            ['NYEIN ZU ZU HAN','AS'],
            ['KAUNG HTET KYAW','PHA'],
            ['KHINE PHOO WAI','AS'],
            ['SHAN HTET AUNG','AS'],
            ['KHINE THAZIN HTUN','AS'],
            ['THWET THWET WAI','AS'],
            ['AUNG KYAW KYAW THANT','AS'],
            ['HNIN WAI AUNG','MNG'],
            ['MOE SANDAR OO','PHA'],
            ['THEINT THEINT MOE','AS'],
            ['THEINGI','AS'],
            ['KHINE THINZAR KYAW','AS'],
            ['HNIN YU HLAING','AS'],
            ['THIRI KAY KHINE','AS'],
            ['HSU MYAT MON','PHA'],
            ['KHINE SABEI','AS'],
            ['EI EI KHIN','PHA'],
            ['EI THINZAR ZAW','TRN'],
            ['YE YINT HTET AUNG','PHA'],
            ['THU YA AUNG','AS'],
            ['THET MYAT NOE','PHA'],
            ['YOON THINZAR TUN','AS'],
            ['MI MI SWE','AS'],
            ['PHONE MYAT SAN','AS'],
            ['HTET OO KHIN','PHA'],
            ['YADANAR MOE','AS'],
            ['SU SU HLAING','AS'],
            ['TINT MARN TUN TUN','AS'],
            ['MU MU NYEIN','TRN'],
            ['CHAW SU SAN','PHA'],
            ['NANDAR AUNG','IC'],
            ['THANT ZIN OO','AS'],
            ['SAW YU NWE','AS'],
            ['ZARCHI NOH NOH','PHA'],
            ['SAW YU NWE','PHA'],
            ['YAMIN OO','AS'],
            ['EI EI MOE CHO','AS'],
            ['PYAE PHYO AUNG','AS'],
            ['THAW DAR SAN','PHA'],
            ['THIN SABEI TIN','PHA'],
            ['SWE THET MAR','IC'],
            ['SAN THIRI TUN','AS'],
            ['MAY HNIN PWINT PHYU','AS'],
            ['ZIN YAWAI TUN','AS'],
            ['ZIN ZIN WAI','TRN'],
            ['MAY LIN LAT AUNG','PHA'],
            ['PHYU HNIN','AS'],
            ['PHONE MYINT KYAW','AS'],
            ['KAY THI NAING','AS'],
            ['AUNG KHANT ZAW','AS'],
            ['YU NANDAR HNIN','MNG'],
            ['SU WAI PHYO','AS'],
            ['THIN ZAR MYO','AS'],
            ['CHO ZIN NEW','AS'],
            ['AYE CHAN AUNG','MNG'],
            ['EI MON AUNG','TRN'],
            ['THIN THIN SWE','PHA'],
            ['CHAR LIN BAT','AS'],
            ['WUTT YE THANT','TRN'],
            ['THAE SU WIN','AS'],
            ['MAY HNIN KHINE','AS'],
            ['ZIN NYEIN KHANT AUNG','AS'],
            ['KYI SOE THEIK','PHA'],
            ['KAUNG HTET KYAW','AS'],
            ['ZWE ZARNI AUNG','AS'],
            ['YE LAY','PHA'],
            ['HSU MYAT WIN','PHA'],
            ['HNIN SHWE YI THAN','AS'],
            ['SU WAI MON','AS'],
            ['ZIN MIN PHYO','AS'],
            ['KHIN THUZAR WIN','PHA'],
            ['ZAW NAING TUN','AS'],
            ['SEINT SAN THU','AS'],
            ['PYAE SONE AUNG','AS'],
            ['PYAE PYAE PHYO','AS'],
            ['THET MYO AYE','TRN'],
            ['AUNG TAYZA','AS'],
            ['HLA HLA MYINT','PHA'],
            ['HIN THIDAR AUNG','PHA'],
            ['WAI PHYO HAN','AS'],
            ['YUNE EI PHYU KYAW','PHA'],
            ['THU NANDAR ZIN','AS'],
            ['HTET HTET KHINE','AS'],
            ['KHINE MON MON THAN','TRN'],
            ['THAE SU MON','AS'],
            ['SANDAR MOE','AS'],
            ['EI THAZIN','AS'],
            ['SANDAR AUNG','AS'],
            ['MAY THET CHAL','AS'],
            ['KYI KYI MAR','AS'],
            ['YUNE THIRI KYAW','AS'],
            ['SAI DUU','AS'],
            ['MYAT NOE KHINE','TRN'],
            ['New Staff','ND'],
            ['New Staff','ND'],
            ['New Staff','ND']
        ];

        foreach($service_staffs as $staff){
            Staff::create([
                'name' => $staff[0], 
                'position' => $staff[1],
                'type_id' => $service_type_id
            ]);
        }

        foreach($second_service_staffs as $staff){
            Staff::create([
                'name' => $staff[0], 
                'position' => $staff[1],
                'type_id' => $second_service_type_id
            ]);
        }

        foreach($lucky_draw_staffs as $staff){
            Staff::create([
                'name' => $staff[0], 
                'position' => $staff[1],
                'type_id' => $lucky_draw_type_id
            ]);
        }
    }
}
